baseurl: "/"
languageCode: "en-gb"
title: "Hasan Asim"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", ]
footnotereturnlinkcontents: "↩"
permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    # - name: About
    #   url: "about/"
    #   weight: 2
    # - name: Categories
    #   url: "categories/"
    #   weight: 3
    # - name: Tags
    #   url: "tags/"
    #   weight: 4
    # - name: Subscribe
    #   url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "
  [Github](https://www.github.com/hasanasim) |
  [LinkedIn](https://www.linkedin.com/in/hasanasim/) |
  [Goodreads](https://www.goodreads.com/user/show/118638265-hasan-asim) |
  [Facebook](https://www.facebook.com/hasanasim134) |
  [Spotify](https://open.spotify.com/user/hasan.asim134?si=fd24d1778b054c6f&nd=1) |
  [Leave me anonymous feedback](https://www.admonymous.co/hasanasim)

   <br> &copy; Hasan Asim {Year}
  "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
